version: '3'
services:

    redis:
        image: 'redis'
        restart: always

    auth_postgres:
        image: postgres
        restart: always
        environment:
            # Use Docker secrets for production
            POSTGRES_PASSWORD: Password123

    secrets_postgres:
        image: postgres
        restart: always
        environment:
            # Use Docker secrets for production
            POSTGRES_PASSWORD: Password321

    secrets_microservice:
        build:
            context: ./secrets_microservice
        restart: always
        volumes:
            - /usr/app/node_modules
            - ./secrets_microservice:/usr/app/

    auth_microservice:
        build:
            context: ./auth_microservice
        restart: always
        volumes:
            - /usr/app/node_modules
            - ./auth_microservice:/usr/app/

    router_microservice:
        build:
            context: ./router_microservice
        restart: always
        volumes:
            - /usr/app/node_modules
            - ./router_microservice:/usr/app/

    angular_client:
        build:
            context: ./angular_client
        restart: always
        volumes:
            - /usr/app/node_modules
            - ./angular_client:/usr/app/

    nginx:
        build:
            context: ./nginx
        restart: always
        ports:
            - 8080:80